name: Java CI with Maven

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:

env:
  x: 15
  y: 16
  z: "ahmed"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    env:
      x: 15
      y: 16
      z: "ahmed"
    steps:
    - name: test
      env:
        x: 15
        y: 16
        z: "ahmed"
      run: |
        echo ${{ env.x }}
        echo ${{ env.z }}
    - name: test
      run: |
        echo ${{ env.y }}
  test:
    needs: build
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: test
      run: |
        echo ${{ vars.DEPI }}