name: Java CI with Maven

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:
concurrency:
  group: 'maven'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: test
      run: |
        sleep 30