name: Java CI with Maven

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: test
      run: |
        echo ${{ vars.DEPI }}
  test:
    needs: build
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: test
      run: |
        echo ${{ vars.DEPI }}