name: prod Java CICD

on:
  workflow_dispatch:

concurrency:
  group: 'java'
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/reusable-workflow.yaml

    with:
      image-name: "prod-java-app"
      environment: "prod"